name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - mac
        - win
        - linux

jobs:
  build-mac:
    runs-on: macos-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.platform == 'all' || github.event.inputs.platform == 'mac' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Package for macOS
      run: npm run dist:mac
      
    - name: Upload macOS Assets
      uses: actions/upload-artifact@v4
      with:
        name: mac-build
        path: release/*.dmg
        retention-days: 30

  build-win:
    runs-on: windows-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.platform == 'all' || github.event.inputs.platform == 'win' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Package for Windows
      run: npm run dist:win
      
    - name: Upload Windows Assets
      uses: actions/upload-artifact@v4
      with:
        name: win-build
        path: release/*.exe
        retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.platform == 'all' || github.event.inputs.platform == 'linux' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Package for Linux
      run: npm run dist:linux
      
    - name: Upload Linux Assets
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: release/*.AppImage
        retention-days: 30

  create-release:
    needs: [build-mac, build-win, build-linux]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/mac-build/*.dmg
          artifacts/win-build/*.exe
          artifacts/linux-build/*.AppImage
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}